GET http://localhost:5050/image/87654321
Content-Type: application/json
Authorization: Bearer {{$dotenv PERMANENT_ACCESS_TOKEN}}

###

POST http://localhost:5050/image/87654321/me-in-the-woods.jpg
Content-Type: application/json
Authorization: Bearer {{$dotenv PERMANENT_ACCESS_TOKEN}}