GET http://localhost:7000/profile/LmalcolmR
Content-Type: application/json
Authorization: Bearer {{$dotenv PERMANENT_ACCESS_TOKEN}}

###

POST http://localhost:7000/profile/LmalcolmR
Content-Type: application/json
Authorization: Bearer {{$dotenv PERMANENT_ACCESS_TOKEN}}

{
    "risk": 1,
    "reward": 2,
    "winPercentage": 3,
    "lossPercentage": 4
}
