GET http://localhost:4500/profile/LmalcolmR
Content-Type: application/json
Authorization: Bearer {{$dotenv PERMANENT_ACCESS_TOKEN}}

###

POST http://localhost:4500/profile/LmalcolmR
Content-Type: application/json
Authorization: Bearer {{$dotenv PERMANENT_ACCESS_TOKEN}}

{
    "lastName": "Gladwell",
    "goalPortfolio": 31000
}
