# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test-startup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Give it a name
    name: Build and Test Startup

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Install npm dependencies from package.json
      - uses: bahmutov/npm-install@v1.6.0
      # Run server starts script
      - run: ./scripts/server-starts.sh
        env: 
          DATABASE_URL: mongodb+srv://root:Q3cuLOWpHMpFhd6D@risk-aversion-backend-d.shiry.azure.mongodb.net/risk-aversion-data?retryWrites=true&w=majority


